#!/bin/sh

#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07
#SBATCH --job-name=bash_bootstraps
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/logs/phomstraps_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/logs/phomstraps_%j.err
#SBATCH --time=7:55:00
#SBATCH --partition=small
#SBATCH --mem=10gb

runfile="/scratch/tyoeasley/brain_representations/src_bash/phom_bootstraps.sh"

### bookkeeping paths ###
base_dir="/scratch/tyoeasley/brain_representations"
subbase_dir="${base_dir}/phom_analysis/full-scale-expmt/within_ICA"
tagfile="${base_dir}/taglist.txt"

### input datasets ###
distlists_fpath="${subbase_dir}/all_distlists.csv"

### run parameters ###
samps=1000
bootstrap_prop=0.8
maxhomdim=1
do_X_phom=1
mem_gb=50

${runfile} -b ${base_dir} -s ${subbase_dir} -t ${tagfile} -f ${distlists_fpath} -n ${samps} -p ${bootstrap_prop} -D ${maxhomdim} -x ${do_X_phom} -m ${mem_gb}
