#!/bin/sh

#SBATCH --job-name=breps_mds
#SBATCH --output=/scratch/tyoeasley/brain_representations/nonPH_analysis/MDS/logs/breps_mds%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/nonPH_analysis/MDS/logs/breps_mds%j.err
#SBATCH --time=167:55:00
#SBATCH --nodes=1 
#SBATCH --tasks-per-node=1
#SBATCH --mem=2gb

script_loc=/scratch/tyoeasley/brain_representations/src_py/comp_MDS.py

dataset_list_name=/scratch/tyoeasley/brain_representations/dist_mtx_list.csv
output_dir=/scratch/tyoeasley/brain_representations/nonPH_analysis/MDS/breps_MDS
namelist_path=/scratch/tyoeasley/brain_representations/BR_label_list.csv

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python ${script_loc} ${dataset_list_name} ${output_dir} ${namelist_path}
