#!/bin/sh

#SBATCH --exclude=node15,node23,node21,node25,node27
#SBATCH --job-name=shbsphoms_PROFUMO_Maps_Psim_dists_XZ
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_Psim_dists_XZ.out%j
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_Psim_dists_XZ.err%j
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

dim=1
ripser_fpath="/scratch/tyoeasley/brain_representations/src_py/interval-matching-precomp_metric/modified_ripser/ripser-image-persistence-simple/ripser-image"

ldmX_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_Psim_dists/dist_mtxs/dXZ__________7b_9t__3f_39t_f__z69_____7z_vv____33Xvv_9dL9vr_1-5___7tsf__v3dv_9_vd--57_P9_3f_-9f_f-_Fv6_393_35v_9_31_b_9___e___9__v_f_3_89_X_25v39_fdx9_6_7_-_vf_v__3_9X_9_8F.ldm"
ldmZ_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_Psim_dists/dist_mtxs/dZ__________7b_9t__3f_39t_f__z69_____7z_vv____33Xvv_9dL9vr_1-5___7tsf__v3dv_9_vd--57_P9_3f_-9f_f-_Fv6_393_35v_9_31_b_9___e___9__v_f_3_89_X_25v39_fdx9_6_7_-_vf_v__3_9X_9_8F.ldm"

outpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_Psim_dists/phom_out/phomXZ__________7b_9t__3f_39t_f__z69_____7z_vv____33Xvv_9dL9vr_1-5___7tsf__v3dv_9_vd--57_P9_3f_-9f_f-_Fv6_393_35v_9_31_b_9___e___9__v_f_3_89_X_25v39_fdx9_6_7_-_vf_v__3_9X_9_8F.txt"


${ripser_fpath} --dim ${dim} --subfiltration ${ldmX_fpath} ${ldmZ_fpath} >> ${outpath}
    
