#!/bin/sh

#SBATCH --exclude=node15,node23,node21,node25,node27
#SBATCH --job-name=shbsphoms_PROFUMO_Maps_inner_dists_YZ
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_inner_dists_YZ.out%j
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_inner_dists_YZ.err%j
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

dim=1
ripser_fpath="/scratch/tyoeasley/brain_representations/src_py/interval-matching-precomp_metric/modified_ripser/ripser-image-persistence-simple/ripser-image"

ldmX_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_inner_dists/dist_mtxs/dYZ__97tu-v79_7__H___vv_r_5593_f3_2_lf_3P_f_8__n_2_Pu_ff____38v77_v_____-__-_7___z_vf3v_77f__f____f___9311__z__9fPf-____n9b_-f9_7-_____L__ffatf_-5__v_-_v_x-f_7__3a7-8_9_78H.ldm"
ldmZ_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_inner_dists/dist_mtxs/dZ__97tu-v79_7__H___vv_r_5593_f3_2_lf_3P_f_8__n_2_Pu_ff____38v77_v_____-__-_7___z_vf3v_77f__f____f___9311__z__9fPf-____n9b_-f9_7-_____L__ffatf_-5__v_-_v_x-f_7__3a7-8_9_78H.ldm"

outpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_inner_dists/phom_out/phomYZ__97tu-v79_7__H___vv_r_5593_f3_2_lf_3P_f_8__n_2_Pu_ff____38v77_v_____-__-_7___z_vf3v_77f__f____f___9311__z__9fPf-____n9b_-f9_7-_____L__ffatf_-5__v_-_v_x-f_7__3a7-8_9_78H.txt"


${ripser_fpath} --dim ${dim} --subfiltration ${ldmX_fpath} ${ldmZ_fpath} >> ${outpath}
    
