#!/bin/sh

#SBATCH --exclude=node15,node23,node21,node25,node27
#SBATCH --job-name=shbsphoms_PROFUMO_Maps_Psim_dists_Y
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_Psim_dists_Y.out%j
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/logs/shbsphoms_PROFUMO_Maps_Psim_dists_Y.err%j
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=7gb

dim=1
ripser_fpath="/scratch/tyoeasley/brain_representations/src_py/interval-matching_bootstrap/modified_ripser/ripser-tight-representative-cycles/ripser-representatives"

ldmX_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_Psim_dists/dist_mtxs/dY___r_3-v_7b7_7v_N1v____9f_P__2__ft23_v33n____5u9__1_9__9__-__T_rfv37-_9a_____93___n3Vv__X-7u_u9____3--_3P8__v8_7__e-___7_-____vf__9ff___--_-_319_-7f_2___-zv-vuX_-__-__8B.ldm"
ldmZ_fpath=""

outpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_Maps/phom_data_PROFUMO_Maps_Psim_dists/phom_out/phomY___r_3-v_7b7_7v_N1v____9f_P__2__ft23_v33n____5u9__1_9__9__-__T_rfv37-_9a_____93___n3Vv__X-7u_u9____3--_3P8__v8_7__e-___7_-____vf__9ff___--_-_319_-7f_2___-zv-vuX_-__-__8B.txt"


${ripser_fpath} --dim ${dim} ${ldmX_fpath} >> ${outpath}
    
