#!/bin/sh

#SBATCH --job-name=ext_ICA
#SBATCH --output=/scratch/tyoeasley/brain_representations/ICA_reps/extract_feats/logs/extICA_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/ICA_reps/extract_feats/logs/extICA_%j.err
#SBATCH --time=23:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50GB

python /scratch/tyoeasley/brain_representations/ICA_reps/extract_feats/feats_from_dtseries.py

