#!/bin/sh

#SBATCH --job-name=pt_cca
#SBATCH --output=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing/logs/pt_cca%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing/logs/pt_cca%j.err
#SBATCH --time=167:55:00
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=3gb

n_workers=3

EB_floc=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing/subj1003_EBs.csv
nperms=30
permlist_floc=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing/tmp_permlist.csv

MATLAB_src=/scratch/tyoeasley/brain_representations/src_MATLAB
py_src=/scratch/tyoeasley/brain_representations/src_py
cwd=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing

script_loc=${py_src}/lindecomp_permtest.py

dataset_fname=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing/svd_reduced_subj_data.brep
output_basedir=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/perm_testing
namelist_path=/scratch/tyoeasley/brain_representations/BR_label_list.csv

# CHECK REGULARIZATION LIST VALUE:
reglist_path=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/reglist_2022Jan02_med.csv

cd ${MATLAB_src}
module load matlab
matlab -nodisplay -nojvm -batch "quickperm_fn(\"${EB_floc}\",${nperms},\"${permlist_floc}\")"
cd ${cwd}

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python ${script_loc} ${dataset_fname} ${output_basedir} ${permlist_floc} ${namelist_path} ${reglist_path} CCA ${n_workers} 
