#!/bin/sh

#SBATCH --job-name=submit_dist_jobs
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/subdists_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/subdists_%j.err
#SBATCH --time=00:05:00
#SBATCH --partition=small
#SBATCH --mem=5gb

runfile="/scratch/tyoeasley/brain_representations/src_bash/calc_dists.sh"

### bookkeeping paths ###
base_dir="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer"

### experiment specifications ###
spec_list_fname="spec_list.txt"

### runtime parameters ###
mem_gb=500
partition="medium"
maxtime_str="167:55:00"

${runfile} -b ${base_dir} -s ${spec_list_fname} -g ${mem_gb} -p ${partition} -t ${maxtime_str}
