#!/bin/sh

#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07
#SBATCH --job-name=match_collate
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/collate_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/collate_%j.err
#SBATCH --time=7:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

runfile="/scratch/tyoeasley/brain_representations/src_bash/collate_matches.sh"

### bookkeeping paths ###
base_dir="/scratch/tyoeasley/brain_representations"
subbase_dir="${base_dir}/phom_analysis/full-scale-expmt/within_Schaefer"
tagfile="${base_dir}/taglist.txt"

### input datasets ###
distlists_fpath="${subbase_dir}/all_distlists.csv"

### run parameters ###
samps=250
match_homdim=1

${runfile} -b ${base_dir} -s ${subbase_dir} -t ${tagfile} -f ${distlists_fpath} -n ${samps} -D ${match_homdim}
