#!/bin/sh

#SBATCH --job-name=stbl_summ
#SBATCH --output=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/stability_testing/logs/stbl_summ%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/stability_testing/logs/stbl_summ%j.err
#SBATCH --time=47:55:00
#SBATCH --mem=80gb

src_dir=/scratch/tyoeasley/brain_representations/src_py
agg_dir=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/stability_testing/CCA_stbl_paragg_2022Jan02
out_dir=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/stability_testing

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python make_stbl_summary.py ${src_dir} ${agg_dir} ${out_dir}
