#!/bin/sh

#SBATCH --job-name=phomCCA_sp
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/logs/phomCCAsp_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/logs/phomCCAsp_%j.err
#SBATCH --time=167:55:00
#SBATCH --mem=750GB

script_loc=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/single_pair/phomCCA_sp.py

lindecomp_path=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/single_pair/pair_lindecomps.nlist
output_basedir=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/single_pair/outputs

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python ${script_loc} ${lindecomp_path} ${output_basedir}
