#!/bin/sh

#SBATCH --job-name=ext_dummy
#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07,node21
#SBATCH --output=/scratch/tyoeasley/brain_representations/dummy_data/extract_feats/logs/extdummy_feats.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/dummy_data/extract_feats/logs/extdummy_feats.err
#SBATCH --time=95:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50GB

python /scratch/tyoeasley/brain_representations/dummy_data/extract_feats/feats_from_dtseries.py

