#!/bin/sh

#SBATCH --job-name=phomCCA_u100
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/logs/phomCCA_u100_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/logs/phomCCA_u100_%j.err
#SBATCH --time=23:55:00
#SBATCH --mem=50GB

script_loc=/scratch/tyoeasley/brain_representations/src_py/lindecomp_phom.py

dataset_list_name=/scratch/tyoeasley/brain_representations/list_of_datalists_U100.csv
output_basedir=/scratch/tyoeasley/brain_representations/phom_analysis/phom_CCA/CCA_Betti_curves_u100
regval_listpath=/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/reglist_2022Jan02_med.csv

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python ${script_loc} ${dataset_list_name} ${output_basedir} ${regval_listpath} CCA 
