#!/bin/sh

#SBATCH --job-name=psimMMP_NM
#SBATCH --output=/scratch/tyoeasley/brain_representations/glasser/NetMats/logs/psim_NM%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/glasser/NetMats/logs/psim_NM%j.err
#SBATCH --time=147:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb


subj_list=/scratch/tyoeasley/brain_representations/glasser/NetMats/subj_list_NM.csv
subj_dist=/scratch/tyoeasley/brain_representations/glasser/NetMats/subj_dists_NM_MMP.csv

cd /scratch/tyoeasley/brain_representations/glasser/NetMats

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python /scratch/tyoeasley/brain_representations/src_py/run_comp_Psim.py ${subj_list} ${subj_dist}
/scratch/tyoeasley/brain_representations/add_to_dists.sh ${subj_dist}

