#!/bin/sh
#SBATCH --job-name=ext_dts_schaefer
#SBATCH --output=/scratch/tyoeasley/brain_representations/schaefer/ext_ptseries/logs/ext_dts_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/schaefer/ext_ptseries/logs/ext_dts_%j.err
#SBATCH --time=23:55:00
#SBATCH --mem=29GB


module load workbench

bash /scratch/tyoeasley/brain_representations/schaefer/ext_ptseries/ext_schaefer_dts.sh 1000 wb_cp
