#!/bin/sh

#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07
#SBATCH --job-name=ICA300Amps_Psim
#SBATCH --output=/scratch/tyoeasley/brain_representations/metric_tests/logs/ICA300Amps_Psim.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/metric_tests/logs/ICA300Amps_Psim.err
#SBATCH --time=23:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

subj_list=/scratch/tyoeasley/brain_representations/metric_tests/ICA300_Amps/subj_list_Amps.csv
subj_sim=/scratch/tyoeasley/brain_representations/metric_tests/ICA300_Amps/ICA300_Amps_Psim_sims.txt

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate Stats
python /scratch/tyoeasley/brain_representations/src_py/comp_sim_mtx.py ${subj_list} ${subj_sim} Psim
if test -f 
then
	echo ${subj_sim} >> /scratch/tyoeasley/brain_representations/metric_tests/ICA300_Amps/AmpsICA300_sims.csv
fi

