#!/bin/sh

#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07
#SBATCH --job-name=unisml_NMs_geodesic_dists_bsph
#SBATCH --output=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/bsphoms_unisml_NMs_geodesic_dists.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/bsphoms_unisml_NMs_geodesic_dists.err
#SBATCH --time=167:55:00
#SBATCH --nodes=3
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

dist_name=/scratch/tyoeasley/brain_representations/metric_tests/unisml_NMs/unisml_NMs_geodesic_dists.txt
outdir=/scratch/tyoeasley/brain_representations/metric_tests/unisml_NMs/phoms_unisml_NMs_geodesic_dists
samps=6

cd ${outdir}

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top
python /scratch/tyoeasley/brain_representations/bootstrap_benchmarks/bootstrap_from_dist_mtx.py ${dist_name} -o ${outdir} -s ${samps} -n 3
	
