#!/bin/sh

#SBATCH --job-name=Schaefer300pNMs_Psim_ztrans
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/Schaefer300pNMs_Psim_ztrans.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/logs/Schaefer300pNMs_Psim_ztrans.err
#SBATCH --partition=medium
#SBATCH --time=167:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=500gb

subj_list=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/Schaefer300_pNMs/subj_list_pNMs.csv
subj_dist=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/Schaefer300_pNMs/Schaefer300_pNMs_Psim_ztrans_dists.txt

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate neuro
python /scratch/tyoeasley/brain_representations/src_py/comp_sim_mtx.py ${subj_list} ${subj_dist} Psim_ztrans True

echo ${subj_dist} >> /scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_Schaefer/Schaefer300_pNMs/pNMsSchaefer300_dists.csv

