#!/bin/sh

#SBATCH --exclude=node15,node23,node21,node25,node27
#SBATCH --job-name=shbsphoms_PROFUMO_spNMs_geodesic_dists_XZ
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/logs/shbsphoms_PROFUMO_spNMs_geodesic_dists_XZ.out%j
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/logs/shbsphoms_PROFUMO_spNMs_geodesic_dists_XZ.err%j
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

dim=1
ripser_fpath="/scratch/tyoeasley/brain_representations/src_py/interval-matching_bootstrap/modified_ripser/ripser-image-persistence-simple/ripser-image"

ldmX_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_geodesic_dists/dist_mtxs/dXZ_89_v1_3_9_77nOqf3_d_vn_19_899f_fXf9f_X7f-__n-__P_f_3___6_-fafr7_v___u9_-3v_nu7___r_9_v________f__8__537_f_f-v___37__2_____d__9f_73_x_3H_8233__9_3___7__ur____fr_v-__3zoH.ldm"
ldmZ_fpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_geodesic_dists/dist_mtxs/dZ_89_v1_3_9_77nOqf3_d_vn_19_899f_fXf9f_X7f-__n-__P_f_3___6_-fafr7_v___u9_-3v_nu7___r_9_v________f__8__537_f_f-v___37__2_____d__9f_73_x_3H_8233__9_3___7__ur____fr_v-__3zoH.ldm"

outpath="/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_geodesic_dists/phom_out/phomXZ_89_v1_3_9_77nOqf3_d_vn_19_899f_fXf9f_X7f-__n-__P_f_3___6_-fafr7_v___u9_-3v_nu7___r_9_v________f__8__537_f_f-v___37__2_____d__9f_73_x_3H_8233__9_3___7__ur____fr_v-__3zoH.txt"


${ripser_fpath} --dim ${dim} --subfiltration ${ldmX_fpath} ${ldmZ_fpath} >> ${outpath}
    
