#!/bin/sh

#SBATCH --job-name=PROFUMO_spNMs_Psim_ztrans_dists_YZ_shbsph
#SBATCH --output=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/shbsphoms_PROFUMO_spNMs_Psim_ztrans_dists_YZ.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/shbsphoms_PROFUMO_spNMs_Psim_ztrans_dists_YZ.err
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

dim=1
ripser_fpath=/scratch/tyoeasley/brain_representations/src_py/interval-matching-precomp_metric/modified_ripser/ripser-image-persistence-simple/ripser-image

ldmX_fpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_Psim_ztrans_dists/dist_mtxs/dYZ_7zv-3-____8____97_Dd28zXf33-Xf_p36s7u9_71b_s_p-f-69s_a1ff__vP-vv_ufZn3-_jc3vr-_1z_5f__9-98-r7e3-5-_9b_3v-f-r_73_fvb-7_tf_4O__9X3__F9_89vf2_vf39-nr3Zvvv29d-f7-9u_2W93f8H.ldm
ldmZ_fpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_Psim_ztrans_dists/dist_mtxs/dZ_7zv-3-____8____97_Dd28zXf33-Xf_p36s7u9_71b_s_p-f-69s_a1ff__vP-vv_ufZn3-_jc3vr-_1z_5f__9-98-r7e3-5-_9b_3v-f-r_73_fvb-7_tf_4O__9X3__F9_89vf2_vf39-nr3Zvvv29d-f7-9u_2W93f8H.ldm

outpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_PROFUMO/PROFUMO_spNMs/phom_data_PROFUMO_spNMs_Psim_ztrans_dists/phom_out/phomYZ_7zv-3-____8____97_Dd28zXf33-Xf_p36s7u9_71b_s_p-f-69s_a1ff__vP-vv_ufZn3-_jc3vr-_1z_5f__9-98-r7e3-5-_9b_3v-f-r_73_fvb-7_tf_4O__9X3__F9_89vf2_vf39-nr3Zvvv29d-f7-9u_2W93f8H.txt


${ripser_fpath} --dim ${dim} --subfiltration ${ldmX_fpath} ${ldmZ_fpath} >> ${outpath}
    
