#!/bin/sh

#SBATCH --exclude=node22,node29,node31,node15,node25,node30,node24,node28,node08,node07
#SBATCH --job-name=uniformNMs_dcor
#SBATCH --output=/scratch/tyoeasley/brain_representations/metric_tests/logs/uniformNMs_dcor.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/metric_tests/logs/uniformNMs_dcor.err
#SBATCH --time=167:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb

subj_list=/scratch/tyoeasley/brain_representations/metric_tests/uniform_NMs/subj_list_NMs.csv
subj_sim=/scratch/tyoeasley/brain_representations/metric_tests/uniform_NMs/uniform_NMs_dcor_sims.txt

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate Stats
python /scratch/tyoeasley/brain_representations/src_py/comp_sim_mtx.py ${subj_list} ${subj_sim} dcor
if test -f 
then
	echo ${subj_sim} >> /scratch/tyoeasley/brain_representations/metric_tests/uniform_NMs/NMsuniform_sims.csv
fi

