#!/bin/sh

#SBATCH --job-name=do_pers_anls
#SBATCH --output=/scratch/tyoeasley/brain_representations/ICA_reps/amplitudes_and_CCA/logs/do_pers_anls%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/ICA_reps/amplitudes_and_CCA/logs/do_pers_anls%j.err
#SBATCH --time=3:55:00
#SBATCH --nodes=1 
#SBATCH --tasks-per-node=1
#SBATCH --mem=100gb

input=/scratch/tyoeasley/brain_representations/ICA_reps/amplitudes_and_CCA/subj_corr_dist.csv
output=/scratch/tyoeasley/brain_representations/ICA_reps/amplitudes_and_CCA/subj_amps_persdiag.npy
script_loc=/scratch/tyoeasley/brain_representations/DistMatrixFiltration.py

source activate alg_top
python ${script_loc} ${input} ${output}
