#!/bin/sh

#SBATCH --job-name=psimPROFUMO_Maps
#SBATCH --output=/scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Maps/logs/psim_Maps%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Maps/logs/psim_Maps%j.err
#SBATCH --time=147:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50gb


subj_list=/scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Maps/subj_list_Maps.csv
subj_psim=/scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Maps/subj_psims_Maps_PROFUMO.csv

cd /scratch/tyoeasley/brain_representations/profumo_reps/HCP_Profumo_cifti_bigdata_1200subs_50modes_smooth_5mm_4runs.ppp/Maps

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate alg_top_neuro
python /scratch/tyoeasley/brain_representations/src_py/comp_Psim_mtx.py ${subj_list} ${subj_psim}
/scratch/tyoeasley/brain_representations/add_to_dists.sh ${subj_psim}

