#!/bin/sh

#SBATCH --job-name=ICA25Amps_Psim
#SBATCH --output=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/logs/ICA25Amps_Psim.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/logs/ICA25Amps_Psim.err
#SBATCH --partition=small
#SBATCH --time=23:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=500gb

subj_list=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/ICA25_Amps/subj_list_Amps.csv
subj_dist=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/ICA25_Amps/ICA25_Amps_Psim_dists.txt

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate neuro
python /scratch/tyoeasley/brain_representations/src_py/comp_sim_mtx.py ${subj_list} ${subj_dist} Psim True

echo ${subj_dist} >> /scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_ICA/ICA25_Amps/AmpsICA25_dists.csv

