#!/bin/sh

#SBATCH --job-name=feats_yeo
#SBATCH --output=/scratch/tyoeasley/brain_representations/yeo/extract_feats/logs/extyeo.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/yeo/extract_feats/logs/extyeo.err
#SBATCH --time=95:55:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --mem=50GB

python /scratch/tyoeasley/brain_representations/yeo/extract_feats/feats_from_dtseries.py

