#!/bin/sh
#SBATCH --job-name=group_grads
#SBATCH --output=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/logs/group_grads_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/logs/group_grads_%j.err
#SBATCH --time=23:55:00
#SBATCH --mem=100GB

src_path=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/compute_group_gradients.py 
dconn_fpath=/scratch/tyoeasley/S1200_dconn_HCP/HCP_S1200_1003_rfMRI_MSMAll_groupPCA_d4500ROW_zcorr.npy
n_comps=300
group_grad_outtype=/scratch/tyoeasley/brain_representations/gradient_reps/gradmaps_d${n_comps}/%s_HCPavgS1200.npy

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate neuro
python ${src_path} ${dconn_fpath} ${group_grad_outtype} -n ${n_comps}
