#!/bin/sh
#SBATCH --job-name=align
#SBATCH --output=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/logs/align_%j.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/logs/align_%j.err
#SBATCH --time=23:55:00
#SBATCH --mem=20GB

src_path=/scratch/tyoeasley/brain_representations/gradient_reps/src/comp_HCP_gradients/align_subj_gradients.py
n_comps=300

subjID_fpath=/scratch/tyoeasley/HCPsubj_subsets/HCP_IDs_all.csv
group_embedding_fpath=/scratch/tyoeasley/brain_representations/gradient_reps/gradmaps_d${n_comps}/emb_HCPavgS1200.npy
subjpath_type=/scratch/tyoeasley/brain_representations/gradient_reps/gradmaps_d${n_comps}/%s_subj-%s.npy
cifti_flag=False

source /export/anaconda/anaconda3/anaconda3-2020.07/bin/activate neuro
python ${src_path} ${subjID_fpath} ${group_embedding_fpath} ${subjpath_type} ${cifti_flag}
