#!/bin/sh

#SBATCH --job-name=grad100_Maps_Psim_dists_YZ_shbsph
#SBATCH --output=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/shbsphoms_grad100_Maps_Psim_dists_YZ.out
#SBATCH --error=/scratch/tyoeasley/brain_representations/bootstrap_benchmarks/logs/shbsphoms_grad100_Maps_Psim_dists_YZ.err
#SBATCH --time=23:55:00
#SBATCH --partition=small
#SBATCH --mem=50gb

dim=1
ripser_fpath=/scratch/tyoeasley/brain_representations/src_py/interval-matching-precomp_metric/modified_ripser/ripser-image-persistence-simple/ripser-image

ldmX_fpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_grad/grad100_Maps/phom_data_grad100_Maps_Psim_dists/dist_mtxs/dYZ__d-d_f-7_uv6vb-f_fe_7-f7ff_35v__a5qDpf7_-__3vDfns3sr57bX33P1f_O_7Xrv3593__-__--__-_5393fx-y_v_X9Pvev6____tda260fv135f9XL3f__5-f_73_q__v3_v-_ve___Wy-335v_33v2_7x5f7_O94D.ldm
ldmZ_fpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_grad/grad100_Maps/phom_data_grad100_Maps_Psim_dists/dist_mtxs/dZ__d-d_f-7_uv6vb-f_fe_7-f7ff_35v__a5qDpf7_-__3vDfns3sr57bX33P1f_O_7Xrv3593__-__--__-_5393fx-y_v_X9Pvev6____tda260fv135f9XL3f__5-f_73_q__v3_v-_ve___Wy-335v_33v2_7x5f7_O94D.ldm

outpath=/scratch/tyoeasley/brain_representations/phom_analysis/full-scale-expmt/within_grad/grad100_Maps/phom_data_grad100_Maps_Psim_dists/phom_out/phomYZ__d-d_f-7_uv6vb-f_fe_7-f7ff_35v__a5qDpf7_-__3vDfns3sr57bX33P1f_O_7Xrv3593__-__--__-_5393fx-y_v_X9Pvev6____tda260fv135f9XL3f__5-f_73_q__v3_v-_ve___Wy-335v_33v2_7x5f7_O94D.txt


${ripser_fpath} --dim ${dim} --subfiltration ${ldmX_fpath} ${ldmZ_fpath} >> ${outpath}
    
